### ISSUE TITLE
Need to get the two digit year...

### ISSUE THREAD

**Issue by soggybag** [mccarthykp/TX-Date-Library#6]
https://github.com/mccarthykp/TX-Date-Library/blob/7fa96fd60763683894b41b887b42d6b4cc5b3a01/src/index.js#L13

Couple ideas. 

- String functions, e.g. slice
- Math e.g. % modulus 

Think about the type that should returned. Full year returns a number this should probably return a number also.

**Comment by mccarthykp** [comment]
return (this._date.getFullYear() % 100);
